### ISSUE TITLE
[Bug]:请求失败,请先登录

### ISSUE THREAD

**Issue by joseph16388** [XiaoXinYo/Easy-Ernie#12]
### 在提交前请确保以下这些

- [X] easy-ernie为最新版本
- [X] 在Issue无法找到它

### 操作系统

Windows

### Python版本

Python 3.10.9

### 问题

venv\lib\site-packages\easy_ernie\ernie.py", line 44, in checkJson
    raise Exception(f'请求失败,{data["msg"]}')
Exception: 请求失败,请先登录

### 触发

from easy_ernie import FastErnie

if __name__ == '__main__':
    BAIDUID = 'XXXX'
    BDUSS_BFESS = 'XXXX'
    fastErnie = FastErnie('BAIDUID', 'BDUSS_BFESS')
    print(fastErnie.ask('你好'))
    # print(fastErnie.ask('我给你发的上一个消息是什么'))
    fastErnie.close()

### 报错

venv\lib\site-packages\easy_ernie\ernie.py", line 44, in checkJson
    raise Exception(f'请求失败,{data["msg"]}')
Exception: 请求失败,请先登录

**Comment by XiaoXinYo** [comment]
你直接给我坐下把，老弟

**Comment by XiaoXinYo** [comment]
刚试了，我这边正常，你看看BAIDUID 和BDUSS_BFESS 是不是正确

**Comment by joseph16388** [comment]
是哦，我都是复制黏贴的
![image](https://github.com/XiaoXinYo/Easy-Ernie/assets/117060507/776d9a31-81af-4acb-a97a-e75d8a49a62a)
E09F69A67223B5EEEB5744DD45B80A02:SL=0:NR=10:FG=1

![image](https://github.com/XiaoXinYo/Easy-Ernie/assets/117060507/1bbbc613-35de-4d2d-b89f-b55881d1e8f3)
FRZcVRGeGg1aUVRcjZoU3BkeFhqc3VoWElLOGtxTjVoeks3bk1WNjYtSlBWUjFsSVFBQUFBJCQAAAAAAAAAAAEAAADY4g4oeXVtaWFuaHVsaTExAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE~I9WRPyPVkS

**Comment by XiaoXinYo** [comment]
我用的你的BAIDUID 和BDUSS_BFESS 可以使用

**Comment by joseph16388** [comment]
> 我用的你的BAIDUID 和BDUSS_BFESS 可以使用

嗯，犯了个低级错误，是可以的，3Q！还要请教下UP手动获取ACS-TOKEN的方法，加你Q了
