### ISSUE TITLE
[Bug]: "'NoneType' object has no attribute 'get'"

### ISSUE THREAD

**Issue by ydengf** [XiaoXinYo/Easy-Ernie#3]
### 在提交前请确保以下这些

- [X] easy_ernie为最新版本
- [X] 在Issue无法找到它

### 操作系统

Linux

### Python版本

Python 3.9.6

### 问题

"'NoneType' object has no attribute 'get'"

### 触发

任何调用都出现

### 报错

"'NoneType' object has no attribute 'get'"

**Comment by XiaoXinYo** [comment]
麻烦提供一下完整的报错信息

**Comment by XiaoXinYo** [comment]
使用ernie.ask也会出现这种情况吗，不使用fasternie
------------------ Original ------------------
From: Yanjiang Deng ***@***.***&gt;
Date: Fri,May 5,2023 11:24 PM
To: XiaoXinYo/Easy-Ernie ***@***.***&gt;
Cc: XiaoXinYo ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [XiaoXinYo/Easy-Ernie] [Bug]: "'NoneType' object has no attribute'get'" (Issue #3)





 
好像就只这个打出来了，fastErnie.ask(ask.prompt) 这句出来的

**Comment by ydengf** [comment]
是的，我换了新的那两个串，两种方式都一样的

**Comment by XiaoXinYo** [comment]
用ernie报错在第几行，可以给下完整的报错截图吗

**Comment by ydengf** [comment]
就报了这一句，没其他的了，你能正常返回么？

**Comment by XiaoXinYo** [comment]
是的，我这里正常返回
![d0e52341aae1b1baeb42a44c68edd84c](https://user-images.githubusercontent.com/56395004/236594643-212ece36-ac59-43db-89fe-a43d7616fc62.png)

**Comment by ydengf** [comment]
确实我就不行，哈哈哈，难道被BAIDU禁用了 
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/34225309/236608245-0334bf0d-1936-455b-828f-fd7c6a0b2f81.png">

**Comment by XiaoXinYo** [comment]
网页端正常使用吗？



发自我的iPhone


------------------ Original ------------------
From: Yanjiang Deng ***@***.***&gt;
Date: Sat,May 6,2023 2:52 PM
To: XiaoXinYo/Easy-Ernie ***@***.***&gt;
Cc: XiaoXinYo ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [XiaoXinYo/Easy-Ernie] [Bug]: "'NoneType' object has no attribute'get'" (Issue #3)





 
确实我就不行，哈哈哈，难道被BAIDU禁用了

**Comment by ydengf** [comment]
也不能，只能另外找个账号了

**Comment by XiaoXinYo** [comment]
方便把 使用ernie.ask报错截图给我吗，我添加 一些 提示



发自我的iPhone


------------------ Original ------------------
From: Yanjiang Deng ***@***.***&gt;
Date: Sat,May 6,2023 3:06 PM
To: XiaoXinYo/Easy-Ernie ***@***.***&gt;
Cc: XiaoXinYo ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [XiaoXinYo/Easy-Ernie] [Bug]: "'NoneType' object has no attribute'get'" (Issue #3)





 
也不能，只能另外找个账号了

**Comment by ydengf** [comment]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/34225309/236608996-1f8f434f-cd39-4762-b30a-3a0468c42cbc.png">
