### ISSUE TITLE
[Bug]: 用你的API之后显示当前账号存在异常，请更换账号再尝试提问

### ISSUE THREAD

**Issue by old-dream321** [XiaoXinYo/Easy-Ernie#4]
### 在提交前请确保以下这些

- [X] easy_ernie为最新版本
- [X] 在Issue无法找到它

### 操作系统

Windows

### Python版本

Python 3.10.7

### 问题

<img width="873" alt="image" src="https://user-images.githubusercontent.com/87767499/236629718-8e88f0de-0de8-47c0-ac41-68b1505dbbdf.png">

### 触发

for data in chatbot.ask( prompt=message,conversation_id=cv_id):
      resp = data
print(resp)

**Comment by XiaoXinYo** [comment]
封号了吧

**Comment by old-dream321** [comment]
。。。干的漂亮

**Comment by XiaoXinYo** [comment]
我用了一个星期没封，看脸🙃
