### ISSUE TITLE
我看到readme上说可能封号，目前有出现封号吗

### ISSUE THREAD

**Issue by Winter-is-comingXK** [XiaoXinYo/Easy-Ernie#7]

**Comment by XiaoXinYo** [comment]
有的


------------------ 原始邮件 ------------------
发件人: Winter-is-comingXK ***@***.***&gt;
发送时间: 2023年5月11日 23:50
收件人: XiaoXinYo/Easy-Ernie ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [XiaoXinYo/Easy-Ernie] 我看到readme上说可能封号，目前有出现封号吗 (Issue #7)
